### ISSUE TITLE
missing corrections and new functionality of 12.5 from codeplex project

### ISSUE THREAD

**Issue by TABUllrich** [OpenSourcePFCLibraries/2017#1]
It seems that a lot of improvements from codeplex project are not in that version.
Why?

**Comment by bruce-armstrong** [comment]
Because I used the last release for the transfer rather than everything that had been checked in so far.

**Comment by TABUllrich** [comment]
It's a pity. There were a lot of bug fixes and good enhancements in the last years. It would be good not to loose them.

**Comment by bruce-armstrong** [comment]
I've just updated the 12.6 code line with the missing changes.  Working on the 2017 code line now.

**Comment by bruce-armstrong** [comment]
2017 has been updated as well.  I didn't create new releases though.

**Comment by TABUllrich** [comment]
Thank you.
I miss some objects under source control: f_removeduplicate, s_classoverview_attrib, pfc_w_debugjson, w_debugjson. (Objects are in PBLs but not under source control)

**Comment by bruce-armstrong** [comment]
Good catch.  I just corrected that.
