### ISSUE TITLE
Wrong declaration for constant values

### ISSUE THREAD

**Issue by TABUllrich** [OpenSourcePFCLibraries/2017#12]
In Powerbuilder it is not possible to declare more than one constant value in one declaration. (Only first declaration will be a constant, the other ones variables!)
So declaration for constant values in pfc_n_cst_environment should be changed.

```
Constant UInt  VER_NT_WORKSTATION       = 1
Constant UInt  VER_NT_SERVER            = 3
...
```

**Comment by bruce-armstrong** [comment]
Corrected
