### ISSUE TITLE
Duplicate property name: anchor?

### ISSUE THREAD

**Issue by TABUllrich** [OpenSourcePFCLibraries/2017#13]
PB 2017 warns for a duplicate property name "anchor" in pfc_n_ostg and pfc_n_ostm?
Had no such warning in PB 12.
I can't find anything about a default property in PB help file. Is this a Powerbuilder bug or a PFC issue?
What is this property for?

**Comment by bruce-armstrong** [comment]
Do a pull, as I just removed those yesterday.  Appears to be some spurious property that was added when those two objects were originally added.
