### ISSUE TITLE
Drop-down DataWindow Search Service bug when Edit Style is DDLB

### ISSUE THREAD

**Issue by CrabbyAppleton** [OpenSourcePFCLibraries/2017#15]
The DDDW search service does not work at all when the edit style of the column is Drop-Down List Box (DDLB).

There are two lines in the pfc_ItemFocusChanged event script in object pfc_n_cst_dwsrv_dropdownsearch in the pfcdwsrv PowerBuilder Library that contain an error:

**Line 103:** Currently reads: "`li_ddlb_index = 0`" but should instead be "`li_ddlb_index = 1`", because the the DO-LOOP UNTIL loop that immediately follows will _always_ exit on the first iteration since `idw_requestor.GetValue(ks_dwcolname, li_ddlb_index)` returns an empty string whenever the column number argument value (li_ddlb_index) is out of range.

**Line 123:** "`Loop Until lb_matchfound Or li_ddlb_index = li_numtabs`" should instead be "`Loop Until lb_matchfound Or li_ddlb_index > li_numtabs`", because the initial value of li_ddlb_index should be 1, not 0.

**Comment by bruce-armstrong** [comment]
If you know the fix then:

1.  Create a branch of the project.
2.  Make the change in your branch.
3.  Issue a push request to send the change back to this project.

**Comment by CrabbyAppleton** [comment]
Thanks for the info on the proper process to follow, Bruce! I'm a GitHub rookie.

The issue has been addressed by kberghall in a better way, so I am closing this issue with no changes to the code.
