### ISSUE TITLE
How to comment changes

### ISSUE THREAD

**Issue by kberghall** [OpenSourcePFCLibraries/2017#26]
Are there some guidelines on how to comment proposed code changes to PFC? There is a comment section when checking an object in, but I assume the code changes should be commented as well, but Is there a comment section at the top of the script that also should be filled in? We add a date and name to all our internal program changes. Like where the current version numbers show? Or is that done automatically at some point? Just trying to provide fixes in the best way possible.

**Comment by bruce-armstrong** [comment]
1. Create your own fork of the project
2. Make the change in your fork
3. Create a pull request to propose the change be included in the main project

http://kbroman.org/github_tutorial/pages/fork.html
