### ISSUE TITLE
pbdom170.pbd pbdom_builder buildFromFile "bad runtime function reference"

### ISSUE THREAD

**Issue by cspmosh** [OpenSourcePFCLibraries/2017#33]
Are there dependencies within this pbd that would cause a deployed PowerBuilder application to crash with a "bad runtime function reference" when calling the buildFromFile function for the pbdom_builder object? Everything runs within the PowerBuilder environment when running the application but after deploying I get the error. Worked with the pbdom126.pbd but not pbdom170. Apologize if this is the wrong place for this. Already submitted a ticket with Appeon.

**Comment by bruce-armstrong** [comment]
The 2017 version of the project should refer to pbdom170.  If it doens't, that's an error.  The PBX will have a dependency on the runtime of PowerBuilder it was built for.

**Comment by cspmosh** [comment]
Our PowerBuilder project is using PowerBuilder 2017 so the pbdom170.pbd should be the correct one. That's why I'm puzzled. I've tried both PowerGen and the deploy option within the powerbuilder IDE to create the exe and both throw the same error at runtime.

**Comment by bruce-armstrong** [comment]
Are you deploying the PBX file along with the PBD?

**Comment by cspmosh** [comment]
No :-\ 

I thought it was either import the pbx or deploy with the pbd. Am I supposed to deploy with the pbx AND the pbd?

**Comment by bruce-armstrong** [comment]
If you import the PBX then you don't need to deploy the PBD.  But it either case you must always deploy the PBX.

**Comment by cspmosh** [comment]
Hmmm, sure enough that fixed it. Odd thing is we never deployed the pbx in version 12.6, just the pbd and it worked. Guess it's possible that the file existed somewhere on the network... I've been stuck on this for a few hours so you've saved me! Thanks for your expertise.
