### ISSUE TITLE
Error number 14 opening dll library pbvm90u.dll in pfc_n_cst_platformunicode object function of_printdlg line 29

### ISSUE THREAD

**Issue by 1646374** [OpenSourcePFCLibraries/2017#35]
Hi,
we just migrated our PB 12.5.2 classic apps to PB2017 R3 and deployed them as 64 bit applications, we are getting error opening dll library pbvm90u.dll when trying to call PFC_PrintDlg function.

Please suggest if there is an alternate solution,
[pbvm90u.docx](https://github.com/OpenSourcePFCLibraries/2017/files/2700585/pbvm90u.docx)

Thanks a lot.
Venu Kokkula

**Comment by bruce-armstrong** [comment]
Did you update the version of PFC you were using?  The dependency on a particular version of the PowerBuilder VM was removed in PFC version 10.

**Comment by 1646374** [comment]
Yes, we did try with the Appeon powerbuilder 2017 pfc libraries.

**Comment by bruce-armstrong** [comment]
I'm not familiar with any Appeon PFC version for 2017.  Last I heard Appeon stopped distributing their own version of PFC and simply provided instructions for eliminating those portions of PFC that aren't supported by PowerServer.

There is no reference to a PowerBuilder runtime DLL in any version of PFC version 10 or later.
