### ISSUE TITLE
new values for pb2019

### ISSUE THREAD

**Issue by mjl38** [OpenSourcePFCLibraries/2017#36]
Hi Bruce,
This is what I've got in my **n_cst_platform.constructor** event. I've added the values for pb2019:
(would be better to do a choose case, I know).

// T3, mjl, 06/01/16: adapt to pb 12.6 instead of 12.5 (see instance vars in ancestor class):
//Protected:
//string		is_separator
//string		is_ClassName[] = {"FNWND3125", "FNWNS3125"} // this is for pb 12.5

// u4, mjl, 11/04/18: see if running pb2017 or pb12.6
// get the version of POWERBUILDER:
n_osversion ln_osver
string ls_PBVMName, ls_PBJavaDLL
ls_PBVMName = ln_osver.of_PBVMName()
if lower(ls_PBVMName) = "pbvm170.dll" then
	is_ClassName[1] = "FNWND3170" // pb2017
	is_ClassName[2] = "FNWNS3170" // pb2017
	is_ClassName[3] = "AfxMDIFrame100su" // pb2017 for "dockable MDI" 
	// v1, mjl, 29/10/19: add version for PB2019
elseif lower(ls_PBVMName) =  "pbvm190.dll" then 
	is_ClassName[1] = "FNWND3190" // pb2019
	is_ClassName[2] = "FNWNS3190" // pb2019
	is_ClassName[3] = "AfxMDIFrame100su" // pb2019 for "dockable MDI", same as PB2017
else	// pb12.6:
	is_ClassName[1] = "FNWND3126" // pb 12.6
	is_ClassName[2] = "FNWNS3126" // pb 12.6
end if

**Comment by bruce-armstrong** [comment]
You should also check the sheet manager service.  That one bases the sheet class name on the version of PowerBuilder.

**Comment by mjl38** [comment]
Hi Bruce,
If you mean the pfc_n_cst_winsrv_sheetmanager object, I cannot find anything that resembles what you are saying. Is it some other object?
regards
